[Maps]
unlocked = ["entrance"]

[Team]
characters = ["seigro_gamma"]
carapace = false
mayfly = false
sensokugol = false
exokiraso = false
items = []
max_spritilo = 12
spritilo = 4
max_ectoplasm = 12
ectoplasm = 4

[seigro_gamma]
health = 5
stamina = 4
mental = 5
rank = 0
status = []
armor = []
weapons = ["scout_carbine", "diverflexo", "stunnade"]
added = []

[ethan_lennox]
health = 5
stamina
mental = 5
rank = 0
status = []
armor = []
weapons = []
added = []
